# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf9742d1820f2695f339a8b7ef8e15130253e92dd2198491572c5e304fe10af9c3c42b4c3842cd8f905eeb17be359f72687e12e66116b1a9b92e9c58e4c9103a

test:
  secret_key_base: 9623d166b4e908638535d5ed9eedf5227825e4f5e9b9f8f2a205388b4cb90349381e24cfb90cb621d9dfae74eb1b5d9c11d6b0e2677b8c32964f858ea759af0d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
